### PR TITLE
bug fix preview page for education would show start and end date for …

### PR DESCRIPTION
**Pull request by SoLetsDev**
ECER-1675: Brief description of the changes

## Description

- bug fix dates showing times on education preview screen 
- Fixed issue where education dates were not showing up on edit after refreshing application. 

## Related jira
- ECER-1687

## Checklist
- [x] I have tested these changes locally.
- [ ] Changes to backend endpoints are covered by passing integration tests.
- [ ] I have added or updated the necessary documentation.

## Screenshots (if applicable)
previous
image

current
image

### CODE REVIEW

**Review by qsl-deepak — COMMENTED** [review]
Can we convert this to datetime type then use a short date format rather than slicing?

**Comment by qsl-deepak** [comment]
For Bug ECER-1675 - I recon we would be needing to format the date at other places/in the future as well, probably best to create a common reusable formatter function for the dates. thoughts?

**Comment by SoLetsDev** [comment]
Changes added. Using a reusable formatter for dates.

**Review by pcatkins — APPROVED** [review]
Nice, looks good!

**Pull request merged**
